{%set version = "3.3.0"%}

package:
  name: selenium
  version: {{ version }}

source:
  fn: selenium-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/selenium/selenium-{{ version }}.tar.gz
  sha256: 43ec925d704928f7a34cb8615354a55a6666b952db2041112473f41e815fb6ab

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - selenium
    - selenium.common
    - selenium.webdriver
    - selenium.webdriver.android
    - selenium.webdriver.chrome
    - selenium.webdriver.common
    - selenium.webdriver.common.html5
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.ie
    - selenium.webdriver.opera
    - selenium.webdriver.phantomjs
    - selenium.webdriver.remote
    - selenium.webdriver.support

about:
  home: https://github.com/SeleniumHQ/selenium/
  license: Apache-2.0
  summary: 'Python bindings for the Selenium WebDriver for automating web browser interaction.'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
