{% set version = "3.8.0" %}

package:
  name: selenium
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/selenium/selenium-{{ version }}.tar.gz
  sha256: 3af07d7a4b5d523540fa4f32902b9dec15e0379862406aef974729f42411053d

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - selenium
    - selenium.common
    - selenium.webdriver
    - selenium.webdriver.android
    - selenium.webdriver.chrome
    - selenium.webdriver.common
    - selenium.webdriver.common.html5
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.ie
    - selenium.webdriver.opera
    - selenium.webdriver.phantomjs
    - selenium.webdriver.remote
    - selenium.webdriver.support

about:
  home: http://www.seleniumhq.org/
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'Python bindings for the Selenium WebDriver for automating web browser interaction.'
  dev_url: https://github.com/SeleniumHQ/selenium/
  doc_url: http://www.seleniumhq.org/docs/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
