{% set name = "selenium" %}
{% set version = "4.38.0" %}

package:
  name: {{ name }}
  version: {{ version }}
source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c117af6727859d50f622d6d0785b945c5db3e28a45ec12ad85cee2e7cc84fc4c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  skip: True  # [py<310]
  missing_dso_whitelist:  # [osx]
    - '*'                 # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - setuptools
    - setuptools-rust
    - wheel
  run:
    - python
    - urllib3 >=2.5.0,<3.0
    # - trio >=0.31.0,<1.0
    - trio >=0.30.0,<1.0
    - trio-websocket >=0.12.2,<1.0
    - certifi >=2025.10.5
    - typing_extensions >=4.15.0,<5.0
    - websocket-client >=1.8.0,<2.0


test:
  imports:
    - selenium
    - selenium.common
    - selenium.types
    - selenium.webdriver.common
    - selenium.webdriver.chrome
    - selenium.webdriver.chromium
    - selenium.webdriver.edge
    - selenium.webdriver.firefox
    - selenium.webdriver.remote
    - selenium.webdriver.ie
    - selenium.webdriver.safari
    - selenium.webdriver.support
    - selenium.webdriver.webkitgtk
    - selenium.webdriver.wpewebkit
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"


about:
  home: https://www.seleniumhq.org
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
  summary: Python bindings for the Selenium WebDriver for automating web browser interaction
  description: |
    Selenium specifically provides an infrastructure for the W3C WebDriver
    specification — a platform and language-neutral coding interface compatible
    with all major web browsers.
  dev_url: https://github.com/SeleniumHQ/selenium
  doc_url: https://www.selenium.dev/documentation

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
