# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JiyTnDQLS5edq1MNxhGTLlAPzFe/BH+Hapr2HH1jhlni6Dfu5SNoSRxuWlCOIXYuwV7RMwSs7PYFOiHaS7jMP1IG7IpWRfNFeEknpGJ1gDri64bD9ZhcPU1NkhCh8ffgPJw7deKI4KJVTdhreBD236MQBuIgFSVyE9zDWU7IrV5P/ulv4dhO02xVHPK6Me6gztHO2qqWofpqVNnAZp1Z0DWoQqOqyhbJg3QlXFmfIAQRS9fHRONr1e4UHXUveR6ULIVPhzEZsCRNCP8o+uO4Pr4uI/aXDqpfe9236usUoH1JkPWwnD/Heo+BWsaI/GDFfa2VdFfUQdEEzhuiCWs1jcq70Kqa7UyTpYyGS7e6y+xGVsIHbiVcfe3JiblN7O7OilaTvM2aTDvglEoqFEG+Thv6VGdtFBxDLIAT3MKwVYSkbWwTKl6DyW6ghfF0uOYQmJxnShSg25ZMVo3y5QcGj+puUsjDf+mJMaTD8UnBUjtEqW2br0+YjdgUX1pgIcIDslk9zlEgj1xTTzQ1xoP7XI3J7Dw65c67UGsO+QOjI1GDVCsH08W+wuGydf/FKmFnKgCXD3aHG2wW85kYoZmYJIU8bnlMDa/mCaYvnI1HekTLRiiQR2HsvO8h769AFZD977burPkfe7Cg2Yf6s+uIEFolQMpPSj5X0CwS0fgkw6U="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
