travis:
  secure:
    BINSTAR_TOKEN: JiyTnDQLS5edq1MNxhGTLlAPzFe/BH+Hapr2HH1jhlni6Dfu5SNoSRxuWlCOIXYuwV7RMwSs7PYFOiHaS7jMP1IG7IpWRfNFeEknpGJ1gDri64bD9ZhcPU1NkhCh8ffgPJw7deKI4KJVTdhreBD236MQBuIgFSVyE9zDWU7IrV5P/ulv4dhO02xVHPK6Me6gztHO2qqWofpqVNnAZp1Z0DWoQqOqyhbJg3QlXFmfIAQRS9fHRONr1e4UHXUveR6ULIVPhzEZsCRNCP8o+uO4Pr4uI/aXDqpfe9236usUoH1JkPWwnD/Heo+BWsaI/GDFfa2VdFfUQdEEzhuiCWs1jcq70Kqa7UyTpYyGS7e6y+xGVsIHbiVcfe3JiblN7O7OilaTvM2aTDvglEoqFEG+Thv6VGdtFBxDLIAT3MKwVYSkbWwTKl6DyW6ghfF0uOYQmJxnShSg25ZMVo3y5QcGj+puUsjDf+mJMaTD8UnBUjtEqW2br0+YjdgUX1pgIcIDslk9zlEgj1xTTzQ1xoP7XI3J7Dw65c67UGsO+QOjI1GDVCsH08W+wuGydf/FKmFnKgCXD3aHG2wW85kYoZmYJIU8bnlMDa/mCaYvnI1HekTLRiiQR2HsvO8h769AFZD977burPkfe7Cg2Yf6s+uIEFolQMpPSj5X0CwS0fgkw6U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
