travis:
  secure:
    BINSTAR_TOKEN: xXBZcamt2e3u1Z4n6L6qwLsHgOD2LsEWR6x5hvWwjRFXlGA+L+TuSBNuI9ay3XzPxVyC4lKkHa13LlvwZfZHNnG8n856N+rslTI+AQPOfrDR8uqyaR9Pa2CLiRzkK0GxB35CYiCqRza2ZsRKlsV7+hgMJjw8N5fpHznrCy07ABs3VfzmlOFADFpKiSEtzAeM8xcoMNWwK+QIMnePfG+k2/am4RG/icmL2BvKKRcFCE/QIX5qLQwUJxjqcgYPriLDkwPzH+6jwDbWYII9SS10t/51pUegGD76cIM0IGmaF/tRV2Aqtu8VS/RlrvOyZmNoJPUHdR1mTg6m2UKMwSd2fPW+/Klbml+KiF4rESW5zI4bOwB0lLCgpv9nJas8ctLXg+ntlJWvwtnIM03vbk0PPsUoSj2J8SR3eYwtyB/JsKxBFjmxTmXej8a4wMd6pH0pc72lssxCyrh9eAlPPIVLWd5v1mipfeJrZTuxcvQNWH+FkqGwTs73j6OyN0I2790Qy4AJzYm21mWCmHg8JH5+9Nj429IZfdQFotowZaa1pwmSjGQSdj0b2J82ia0sHM8OqmVUPJdXtSvXmDKAjdiR+YzKZnDz1ce9Y7RfzaQYIYW8uyN455edbL3QEpyhUQruMs2pSHTUJGbLr/moZ04z8LCPaQG5/pcuDXiO0TY1RZI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
